services:
  aphw-ddi-register-importer:
    build:
      context: .
      target: production
    image: aphw-ddi-register-importer
    container_name: aphw-ddi-register-importer
    environment:
      APPINSIGHTS_CLOUDROLE: aphw-ddi-register-importer-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-test}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-test}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-test}
      REGISTER_IMPORT_REQUEST_QUEUE: ${REGISTER_IMPORT_REQUEST_QUEUE:-aphw-ddi-register-import-request}${MESSAGE_QUEUE_SUFFIX}
      EVENTS_TOPIC_ADDRESS: ${EVENT_TOPIC_ADDRESS:-dangerous-dogs-index-events}${MESSAGE_QUEUE_SUFFIX}
      EVENTS_SUBSCRIPTION_ADDRESS: ${EVENT_SUBSCRIPTION_ADDRESS:-dangerous-dogs-index-event-hub}${MESSAGE_QUEUE_SUFFIX}
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"

  aphw-ddi-register-importer-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.23.0
    command: "azurite --skipApiVersionCheck --loose --blobHost 0.0.0.0"
