# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  aphw-ddi-register-importer:
    build:
      target: development
    image: aphw-ddi-register-importer-development
    container_name: aphw-ddi-register-importer-test
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
    depends_on:
      - aphw-ddi-register-importer-azurite
    environment:
      AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://aphw-ddi-register-importer-azurite:10000/devstoreaccount1"

  aphw-ddi-register-importer-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.23.0
<<<<<<< HEAD
    ports: 
      - "10000:10000"

=======
    
>>>>>>> parent of 2db945f (Update storage connection docker compose)
