services:
  aphw-ddi-register-importer:
    build:
      context: .
      target: production
    image: aphw-ddi-register-importer
    container_name: aphw-ddi-register-importer
    environment:
      APPINSIGHTS_CLOUDROLE: aphw-ddi-register-importer-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
