{{- include "ffc-helm-library.container-config-map" (list . "aphw-ddi-register-importer.config-map") -}}
{{- define "aphw-ddi-register-importer.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
{{- end -}}
