{{- include "ffc-helm-library.container-secret" (list . "aphw-ddi-register-importer.container-secret") -}}
{{- define "aphw-ddi-register-importer.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  AZURE_STORAGE_CONNECTION_STRING: {{ quote .Values.container.azureStorageConnectionString }}
  AZURE_STORAGE_ACCOUNT_NAME: {{ quote .Values.container.azureStorageAccountName }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  MESSAGE_QUEUE_PASSWORD: {{ quote .Values.container.messageQueuePassword }}
  MESSAGE_QUEUE_USER: {{ quote .Values.container.messageQueueUser }}
  {{- end }}
{{- end -}}
