{{- include "ffc-helm-library.container-secret" (list . "aphw-ddi-register-importer.container-secret") -}}
{{- define "aphw-ddi-register-importer.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
{{- end -}}
