environment: production
environmentCode:
name: aphw-ddi-register-importer
namespace: aphw-ddi
workstream: aphw-ddi
image: aphw-ddi-register-importer

labels:
  component: service

appInsights:
  connectionString:

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

containerConfigMap:
  name: aphw-ddi-register-importer-config-map

containerSecret:
  name: aphw-ddi-register-importer-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageAccountName: aphwddi
  importRequestQueueAddress: aphw-ddi-register-import-request
  messageQueueHost: host
  messageQueuePassword: password
  messageQueueUser: user

aadPodIdentity: true
